language: node_js
node_js:
  - node
  - 8
  - 9
  - 10

cache: npm

before_install: npm i -g npm@latest
install:
  - npm ci
  - npm i monaco-editor react

deploy:
  provider: npm
  skip-cleanup: true
  email: "nikeee@outlook.com"
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true
    node: node

git:
depth: 1
